import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Under Construction!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Under Construction!&nbsp;
            <code className={styles.code}></code>
          </p>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/warning.png"
            alt="warning sign"
            width={500}
            height={500}
            priority
          />
        </div>
      </main>
    </>
  )
}
